
kl_weight: 0.01
adv_weight: 0.1
perceptual_weight: 0.01
lambda_weight: 0.1
bank_size: 64
generator_lr: 5e-4
discriminator_lr: 1e-5
fft_weight: 0.1
gradient_weight: 0.1

vae_kwgs:
  spatial_dims: 3      
  in_channels: 1
  out_channels: 1
  num_res_blocks: 2
  latent_channels: 4
  attention_levels: [False, False, False, True]
  norm_num_groups: 32

velocity_kwargs:
  spatial_dims: 3
  in_channels: 8
  out_channels: 4
  channels: [64,128,256]
  attention_levels: [False, True, True]
  num_res_blocks: 2
  num_head_channels: 32
  with_conditioning: False
#  cross_attention_dim: 256

detectorproj_kwargs:
  in_channels: 21
  proj_hidden: 128
  embed_dim: 4
  latent_spatial_shape: [32, 32, 8]


ct_train_params:
  lr: 1e-4